### PR TITLE
Commit for fix and test to check duplicate artifact id

### LINKED ISSUE #69: running 'yo alfresco:amp' twice with same artifact id
When we run `yo alfresco:amp` twice with the same 'artifact id' it will be good to let the user know that an amp with the same name exists and if they want to exit(default) or proceed to overwrite.

### PR DESCRIPTION
**Pull request by vprince1**
fixes #69 

This fix does not work with Node 5.1 (failing with the same lodash error as master).

### CODE REVIEW

File: generators/base-generator.js [hunk 1]
```diff
@@ -117,7 +117,9 @@ module.exports = yeoman.Base.extend({
             return prompt.commonFilter.call(this, input);
           }.bind(this);
         }
-        if (!prompt.hasOwnProperty('validate') && prompt.hasOwnProperty('name')) {
+        if (prompt.hasOwnProperty('validate')) {
+          newPrompt.validate = newPrompt.validate.bind(this);
```
Comment (vprince1) [inline generators/base-generator.js]: I modified this code to only bind 'this' with validate method. I am not sure if this is the correct way to handle this.

File: generators/common/prompt-validators.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+      return _.isEmpty(validatorArray) ? undefined : validatorArray.reduce(function (previousValue, validator) {
+        return (previousValue === true) ? validator.call(this, input) : previousValue;
+      }.bind(this), true);
+    };
+  },
+
+  uniqueSourceAmpModuleValidator: function (input, context) {
+    debug('uniqueSourceAmpModuleValidator(%s)', input);
+    if (_.isEmpty(input)) return 'Artifact Id cannot be empty';
+    var moduleRegistry = require('./alfresco-module-registry.js')(_.isEmpty(this.config) ? context : this);
```
Comment (vprince1) [inline generators/common/prompt-validators.js]: The 'context' argument is only used when running tests. Is this ok or is there a better way to handle it?

File: generators/base-generator.js (hunk 1 above)
Comment (binduwavell) [inline generators/base-generator.js]: Yeah, I'm not sure we should do this, unless we go through and add the binding to all other user supplied prompt functions. My inclination is to not do this and to do it in the prompt definition. In the case of the generated functions we have to perform this binding because the user essentially doesn't have a way to control that. ... or maybe they do... hmm... I should probably think on this some more... :)

File: generators/common/prompt-validators.js (hunk 2 above)
Comment (binduwavell) [inline generators/common/prompt-validators.js]: Why not just pass the module registry in?

**Comment by binduwavell** [comment]
Generally this looks really good. I want to get the tests fixed before merging just so we can be certain it merges clean. Thanks @vprince1 !!!

**Comment by vprince1** [comment]
Clicking on 'Details' link on codecov/project takes me to a 404 error page.. Is there something I should do?

**Comment by binduwavell** [comment]
Not sure, maybe we can screen share. I'll also take a look to get and see
if there are permissions I have to setup.

**Comment by vprince1** [comment]
I see the attached image when I click the link "https://codecov.io/gh/binduwavell/generator-alfresco/compare/c7c534fcb91860605342c695f9dbc889c65c67b1...ff4588e46880f96a57de2c6d2856dcf18011bf52"

image

**Comment by binduwavell** [comment]
Did you rebase your branch since the graph was built last?

**Comment by vprince1** [comment]
I rebased before the commit.

**Comment by binduwavell** [comment]
From what I'm seeing in the codecov console it may be related to that. I
have reached out to them to ask if they can investigate.
